# Generated by Django 3.2.20 on 2024-04-06 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_labels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('company', models.CharField(blank=True, max_length=30, null=True, verbose_name='회사')),
                ('position', models.CharField(blank=True, max_length=30, null=True, verbose_name='직책')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('profile_image_url', models.URLField(blank=True, null=True, verbose_name='프로필 사진')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('website', models.URLField(blank=True, null=True, verbose_name='웹사이트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('labels', models.ManyToManyField(blank=True, related_name='contacts', to='contacts.ContactLabel', verbose_name='라벨')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
